---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cds-user
  namespace: cds

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cds-user-full-access
  namespace: cds
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cds-user-view
  namespace: cds
subjects:
- kind: ServiceAccount
  name: cds-user
  namespace: cds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cds-user-full-access
